--================================== InitiationDetail Log Trigger ==============================

CREATE TRIGGER [tr_InitiationDetail]
    ON [InitiationDetail]
    AFTER UPDATE, DELETE
    AS BEGIN
	DECLARE @VLogId int,@activity varchar(20);
	SELECT @VLogId=isnull(MAX(LogId),0)+1 FROM InitiationDetail_log

		IF EXISTS(SELECT * FROM INSERTED) AND EXISTS (SELECT * from DELETED) 
		BEGIN
			SET @activity='UPDATE'
		END
		ELSE IF EXISTS (SELECT * from DELETED) 
		BEGIN
			SET @activity='DELETE'
		END
		ELSE IF EXISTS (SELECT * from INSERTED) 
		BEGIN
			SET @activity='INSERT'
		END

		IF EXISTS(SELECT * FROM INSERTED) 
		BEGIN
			INSERT INTO InitiationDetail_log 
				(Id	,
				RefId	,
				DepartmentId	,
				RoleTypeId,
				CustomerName	,
				EntityTypeId	,
				EntityId	,
				CustomerTypeId	,
				AgreementId	,
				AgreementOthers	,
				PaymentTermId	,
				PaymentTermOthers	,
				OfficeAddress	,
				OfficeAddress1	,
				OfficeCountryId	,
				OfficeOtherCountry	,
				OfficeStateId	,
				OfficeOtherState	,
				OfficeCityId	,
				OfficeOtherCity	,
				DLNumber	,
				IsOfficeDLAddressSame	,
				DLAddress	,
				DLAddress1	,
				DLCountryId	,
				DLOtherCountry	,
				DLStateId	,
				DLOtherState	,
				DLCityId	,
				DLOtherCity	,
				PANNumber	,
				GSTNumber	,
				IsDLBillingAddressSame	,
				BillingAddress	,
				BillingAddress1	,
				BillingCountryId	,
				BillingOtherCountry	,
				BillingStateId	,
				BillingOtherState	,
				BillingCityId	,
				BillingOtherCity	,
				AuthorisedSignatoryName	,
				ContactPersonName	,
				ContactPersonMobile	,
				ContactPersonEmail	,
				PartyProfileSheet_FileName	,
				PartyProfileSheet_Extension	,
				DraftAgreement_FileName	,
				DraftAgreement_Extension	,
				Comment	,
				RequestStatusId	,
				IsActive	,
				CreatedById	,
				CreateDate	,
				ModifiedById	,
				ModifyDate,
				[LogId],
				[LogDate],
				[Data],
				[Action])
			SELECT 
				Id,
				RefId,
				DepartmentId	,
				RoleTypeId,
				CustomerName	,
				EntityTypeId	,
				EntityId	,
				CustomerTypeId	,
				AgreementId	,
				AgreementOthers	,
				PaymentTermId	,
				PaymentTermOthers	,
				OfficeAddress	,
				OfficeAddress1	,
				OfficeCountryId	,
				OfficeOtherCountry	,
				OfficeStateId	,
				OfficeOtherState	,
				OfficeCityId	,
				OfficeOtherCity	,
				DLNumber	,
				IsOfficeDLAddressSame	,
				DLAddress	,
				DLAddress1	,
				DLCountryId	,
				DLOtherCountry	,
				DLStateId	,
				DLOtherState	,
				DLCityId	,
				DLOtherCity	,
				PANNumber	,
				GSTNumber	,
				IsDLBillingAddressSame	,
				BillingAddress	,
				BillingAddress1	,
				BillingCountryId	,
				BillingOtherCountry	,
				BillingStateId	,
				BillingOtherState	,
				BillingCityId	,
				BillingOtherCity	,
				AuthorisedSignatoryName	,
				ContactPersonName	,
				ContactPersonMobile	,
				ContactPersonEmail	,
				PartyProfileSheet_FileName	,
				PartyProfileSheet_Extension	,
				DraftAgreement_FileName	,
				DraftAgreement_Extension	,
				Comment	,
				RequestStatusId	,
				IsActive	,
				CreatedById	,
				CreateDate	,
				ModifiedById	,
				ModifyDate,
				@VLogId,
				GETDATE(),
				'New value',
				@activity
		FROM INSERTED
	END

	IF EXISTS (SELECT * FROM DELETED)
		BEGIN
			INSERT INTO InitiationDetail_log 
				(Id	,
				RefId	,
				DepartmentId	,
				RoleTypeId,
				CustomerName	,
				EntityTypeId	,
				EntityId	,
				CustomerTypeId	,
				AgreementId	,
				AgreementOthers	,
				PaymentTermId	,
				PaymentTermOthers	,
				OfficeAddress	,
				OfficeAddress1	,
				OfficeCountryId	,
				OfficeOtherCountry	,
				OfficeStateId	,
				OfficeOtherState	,
				OfficeCityId	,
				OfficeOtherCity	,
				DLNumber	,
				IsOfficeDLAddressSame	,
				DLAddress	,
				DLAddress1	,
				DLCountryId	,
				DLOtherCountry	,
				DLStateId	,
				DLOtherState	,
				DLCityId	,
				DLOtherCity	,
				PANNumber	,
				GSTNumber	,
				IsDLBillingAddressSame	,
				BillingAddress	,
				BillingAddress1	,
				BillingCountryId	,
				BillingOtherCountry	,
				BillingStateId	,
				BillingOtherState	,
				BillingCityId	,
				BillingOtherCity	,
				AuthorisedSignatoryName	,
				ContactPersonName	,
				ContactPersonMobile	,
				ContactPersonEmail	,
				PartyProfileSheet_FileName	,
				PartyProfileSheet_Extension	,
				DraftAgreement_FileName	,
				DraftAgreement_Extension	,
				Comment	,
				RequestStatusId	,
				IsActive	,
				CreatedById	,
				CreateDate	,
				ModifiedById	,
				ModifyDate,
				[LogId],
				[LogDate],
				[Data],
				[Action])
			SELECT 
				Id,
				RefId,
				DepartmentId	,
				RoleTypeId ,
				CustomerName	,
				EntityTypeId	,
				EntityId	,
				CustomerTypeId	,
				AgreementId	,
				AgreementOthers	,
				PaymentTermId	,
				PaymentTermOthers	,
				OfficeAddress	,
				OfficeAddress1	,
				OfficeCountryId	,
				OfficeOtherCountry	,
				OfficeStateId	,
				OfficeOtherState	,
				OfficeCityId	,
				OfficeOtherCity	,
				DLNumber	,
				IsOfficeDLAddressSame	,
				DLAddress	,
				DLAddress1	,
				DLCountryId	,
				DLOtherCountry	,
				DLStateId	,
				DLOtherState	,
				DLCityId	,
				DLOtherCity	,
				PANNumber	,
				GSTNumber	,
				IsDLBillingAddressSame	,
				BillingAddress	,
				BillingAddress1	,
				BillingCountryId	,
				BillingOtherCountry	,
				BillingStateId	,
				BillingOtherState	,
				BillingCityId	,
				BillingOtherCity	,
				AuthorisedSignatoryName	,
				ContactPersonName	,
				ContactPersonMobile	,
				ContactPersonEmail	,
				PartyProfileSheet_FileName	,
				PartyProfileSheet_Extension	,
				DraftAgreement_FileName	,
				DraftAgreement_Extension	,
				Comment	,
				RequestStatusId	,
				IsActive	,
				CreatedById	,
				CreateDate	,
				ModifiedById	,
				ModifyDate,
				@VLogId,
				GETDATE(),
				'Old value',
				@activity
		FROM DELETED
	END
    END;
