namespace Core.Models.Response;

public class ContractReportResponse
{
    public string CustomerName { get; set; }
    public string Entity { get; set; }
    public string EntityType { get; set; }
    public string CustomerType { get; set; }
    public string Agreement { get; set; }
    public string PaymentTerm { get; set; }
    public string OfficeAddress { get; set; }
    public string OfficeAddress1 { get; set; }
    public string OfficeCountry { get; set; }
    public string OfficeOtherCountry { get; set; }
    public string OfficeState { get; set; }
    public string OfficeOtherState { get; set; }
    public string OfficeCity { get; set; }
    public string OfficeOtherCity { get; set; }
    public string OfficePinNo { get; set; }
    public string DLAddress { get; set; }
    public string DLAddress1 { get; set; }
    public string DLCountry { get; set; }
    public string DLOtherCountry { get; set; }
    public string DLState { get; set; }
    public string DLOtherState { get; set; }
    public string DLCity { get; set; }
    public string DLOtherCity { get; set; }
    public string DLPinNo { get; set; }
    public string BillingAddress { get; set; }
    public string BillingAddress1 { get; set; }
    public string BillingCountry { get; set; }
    public string BillingOtherCountry { get; set; }
    public string BillingState { get; set; }
    public string BillingOtherState { get; set; }
    public string BillingCity { get; set; }
    public string BillingOtherCity { get; set; }
    public string BillingPinNo { get; set; }
    public string DeliveryAddress { get; set; }
    public string DeliveryAddress1 { get; set; }
    public string DeliveryCountry { get; set; }
    public string DeliveryOtherCountry { get; set; }
    public string DeliveryState { get; set; }
    public string DeliveryOtherState { get; set; }
    public string DeliveryCity { get; set; }
    public string DeliveryOtherCity { get; set; }
    public string DeliveryPinNo { get; set; }
    public string MarketedByAddress { get; set; }
    public string MarketedAddress { get; set; }
    public string DLNumber { get; set; }
    public string PANNumber { get; set; }
    public string GSTNumber { get; set; }
    public string AuthorisedSignatoryName { get; set; }
    public string ContactPersonName { get; set; }
    public string ContactPersonMobile { get; set; }
    public string ContactPersonEmail { get; set; }
    public string Comment { get; set; }
    public string AgreementDate { get; set; }
    public string EffectiveDate { get; set; }
    public string TermValidityId { get; set; }
    public string RenewalDueDate { get; set; }
    public string TermValidityNo { get; set; }
    public string YearNotice { get; set; }
    public string MonthNotice { get; set; }
    public string DayNotice { get; set; }
    public string Country { get; set; }
    public string StateName { get; set; }
    public string OtherExecutionState { get; set; }
    public string City { get; set; }
    public string OtherExecutionCity { get; set; }
    public string ExecutionComment { get; set; }
    public string OtherRemarks { get; set; }
}
